package lint

import (
	"path/filepath"
	"strings"
	"testing"
)

func TestBehaviorCloneRequiresExplicitSuppressionReason(t *testing.T) {
	tmp := newTestModule(t)
	writeFile(t, filepath.Join(tmp, "sample.go"), `package sample

func First(value int) int {
	next := value + 1
	if next > 10 { return next * 2 }
	return next
}

//slopelint:ignore behavior_clone
func MissingReason(input int) int {
	next := input + 1
	if next > 10 { return next * 2 }
	return next
}

//slopelint:ignore behavior_clone -- separate protocol boundary
func Suppressed(input int) int {
	next := input + 1
	if next > 10 { return next * 2 }
	return next
}
`)

	joined := joinMessages(lintInDir(t, tmp))
	if !strings.Contains(
		joined,
		`function "MissingReason" has same supported behavior as "First"`,
	) {
		t.Fatalf("reasonless directive suppressed clone:\n%s", joined)
	}

	if strings.Contains(joined, `function "Suppressed" has same supported behavior`) {
		t.Fatalf("explicit suppression ignored:\n%s", joined)
	}
}

func TestBehaviorCloneSuppressesExplicitBlockOnly(t *testing.T) {
	tmp := newTestModule(t)
	writeFile(t, filepath.Join(tmp, "sample.go"), `package sample

var errBad error
type request struct { name, kind, scope string; size int }

func First(value request) error {
	if value.name == "" { return errBad }
	if value.kind == "" { return errBad }
	if value.size == 0 { return errBad }
	if value.scope == "" { return errBad }
	return nil
}

func Second(value request) error {
	//slopelint:ignore behavior_clone -- validation stays at API boundary
	if value.name == "" { return errBad }
	if value.kind == "" { return errBad }
	if value.size == 0 { return errBad }
	if value.scope == "" { return errBad }
	return errBad
}
`)

	joined := joinMessages(lintInDir(t, tmp))
	if strings.Contains(joined, `behavior block in "Second" duplicates block in "First"`) {
		t.Fatalf("explicit block suppression ignored:\n%s", joined)
	}
}

func TestBehaviorCloneAutoSuppressesGeneratedCode(t *testing.T) {
	tmp := newTestModule(t)
	source := `// Code generated by test generator. DO NOT EDIT.

package sample

func First(value int) int {
	next := value + 1
	if next > 10 { return next * 2 }
	return next
}

func Second(input int) int {
	next := input + 1
	if next > 10 { return next * 2 }
	return next
}
`
	writeFile(t, filepath.Join(tmp, "generated.go"), source)

	joined := joinMessages(lintInDir(t, tmp))
	if strings.Contains(joined, "has same supported behavior") ||
		strings.Contains(joined, "duplicates block") {
		t.Fatalf("generated behavior clone reported:\n%s", joined)
	}
}

func TestBehaviorCloneAutoSuppressesMechanicalClosures(t *testing.T) {
	tmp := newTestModule(t)
	writeFile(t, filepath.Join(tmp, "sample.go"), `package sample

import (
	"context"
	"errors"
	"sort"
)

type lock struct{}
func (*lock) Release(context.Context) error { return nil }

type file struct { Path string }

func First(ctx context.Context, lock *lock, files []file) (err error) {
	defer func() { err = errors.Join(err, lock.Release(ctx)) }()
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	return errors.New("first")
}

func Second(ctx context.Context, lock *lock, files []file) (err error) {
	defer func() { err = errors.Join(err, lock.Release(ctx)) }()
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	return errors.New("first")
}
`)

	joined := joinMessages(lintInDir(t, tmp))
	if strings.Contains(joined, `function "Second closure" has same supported behavior`) {
		t.Fatalf("mechanical closure clone reported:\n%s", joined)
	}

	if !strings.Contains(joined, `function "Second" has same supported behavior as "First"`) {
		t.Fatalf("parent function behavior disappeared:\n%s", joined)
	}
}

func TestBehaviorCloneAutoSuppressesInterfaceRequiredForwarders(t *testing.T) {
	tmp := newTestModule(t)
	writeFile(t, filepath.Join(tmp, "contract", "contract.go"), `package contract

type Part struct { Value int }

type Flusher interface {
	FlushPrimary(Part, Part, Part, Part, Part, Part) int
	FlushSecondary(Part, Part, Part, Part, Part, Part) int
}
`)
	writeFile(t, filepath.Join(tmp, "impl", "impl.go"), `package impl

import "example.com/sample/contract"

type writer struct{}

func flushBuffer(a, b, c, d, e, f int) int {
	return a + b + c + d + e + f
}

func (writer) FlushPrimary(a, b, c, d, e, f contract.Part) int {
	return flushBuffer(a.Value, b.Value, c.Value, d.Value, e.Value, f.Value)
}
func (writer) FlushSecondary(a, b, c, d, e, f contract.Part) int {
	return flushBuffer(a.Value, b.Value, c.Value, d.Value, e.Value, f.Value)
}

var _ contract.Flusher = writer{}
`)

	joined := joinMessages(lintInDir(t, tmp))
	if strings.Contains(
		joined,
		`function "(writer).FlushSecondary" has same supported behavior`,
	) {
		t.Fatalf("interface-required forwarder clone reported:\n%s", joined)
	}
}

func TestBehaviorCloneKeepsCustomComparatorClosures(t *testing.T) {
	tmp := newTestModule(t)
	writeFile(t, filepath.Join(tmp, "sample.go"), `package sample

type file struct { Path string }

func consume([]file, func(int, int) bool) {}

func First(files []file) {
	consume(files, func(i, j int) bool { return files[i].Path < files[j].Path })
}

func Second(files []file) {
	consume(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	println(len(files))
}
`)

	joined := joinMessages(lintInDir(t, tmp))
	if !strings.Contains(joined, `function "Second closure" has same supported behavior`) {
		t.Fatalf("custom comparator clone suppressed:\n%s", joined)
	}
}

func TestBehaviorCloneKeepsSubstantialDeferredClosures(t *testing.T) {
	tmp := newTestModule(t)
	writeFile(t, filepath.Join(tmp, "sample.go"), `package sample

func First(value *int) {
	defer func() {
		*value++
		if *value > 10 { *value *= 2 }
		println(*value)
	}()
}

func Second(value *int) {
	defer func() {
		*value++
		if *value > 10 { *value *= 2 }
		println(*value)
	}()
	println("second")
}
`)

	joined := joinMessages(lintInDir(t, tmp))
	if !strings.Contains(joined, `function "Second closure" has same supported behavior`) {
		t.Fatalf("substantial deferred closure suppressed:\n%s", joined)
	}
}

func TestBehaviorCloneKeepsNonInterfaceForwarders(t *testing.T) {
	tmp := newTestModule(t)
	writeFile(t, filepath.Join(tmp, "sample.go"), `package sample

type writer struct{}
type part struct { value int }

func transform(a, b, c, d, e, f int) int {
	return a + b + c + d + e + f
}

func (writer) First(a, b, c, d, e, f part) int {
	return transform(a.value, b.value, c.value, d.value, e.value, f.value)
}
func (writer) Second(a, b, c, d, e, f part) int {
	return transform(a.value, b.value, c.value, d.value, e.value, f.value)
}
`)

	joined := joinMessages(lintInDir(t, tmp))
	if !strings.Contains(
		joined,
		`function "(writer).Second" has same supported behavior as "(writer).First"`,
	) {
		t.Fatalf("non-interface forwarder clone suppressed:\n%s", joined)
	}
}
