package lint

import (
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"sync"
	"testing"
)

func TestPackageRepoFilesExcludeCompilerGeneratedCGoFiles(t *testing.T) {
	t.Parallel()

	const testSourceFilename = "sample.go"

	dir := t.TempDir()
	generated := filepath.Join(t.TempDir(), "_cgo_gotypes.go")

	files, err := packageRepoFiles(&packageMeta{
		Dir:             dir,
		ImportPath:      "example.com/sample",
		GoFiles:         []string{testSourceFilename},
		CgoFiles:        []string{"native.go"},
		CompiledGoFiles: []string{testSourceFilename, generated},
	})
	if err != nil {
		t.Fatal(err)
	}

	want := []string{filepath.Join(dir, testSourceFilename), filepath.Join(dir, "native.go")}
	if len(files) != len(want) || files[0] != want[0] || files[1] != want[1] {
		t.Fatalf("source files = %#v, want %#v", files, want)
	}
}

func TestPackageAnalysisFilesDropOnlyGeneratedCompilerCacheFiles(t *testing.T) {
	t.Parallel()

	packageDir := t.TempDir()
	fset := token.NewFileSet()

	repoFile, err := parser.ParseFile(
		fset,
		filepath.Join(packageDir, "generated.go"),
		"// Code generated by test. DO NOT EDIT.\npackage sample\n",
		parser.ParseComments,
	)
	if err != nil {
		t.Fatal(err)
	}

	compilerFile, err := parser.ParseFile(
		fset,
		filepath.Join(t.TempDir(), "_cgo_gotypes.go"),
		"// Code generated by cmd/cgo; DO NOT EDIT.\npackage sample\n",
		parser.ParseComments,
	)
	if err != nil {
		t.Fatal(err)
	}

	got := packageAnalysisFiles([]*ast.File{repoFile, compilerFile}, fset, packageDir)
	if len(got) != 1 || got[0] != repoFile {
		t.Fatalf("analysis files = %#v, want repo generated file only", got)
	}
}

const (
	testSupportFixturePath = "internal/fixture"
	testSupportMixedPath   = "internal/mixed"
	testSupportFixtureFile = testSupportFixturePath + "/helper.go"
	testSupportMixedFile   = testSupportMixedPath + "/helper.go"
	testSupportUnusedFile  = "internal/unused/helper.go"
	testSupportLeafFile    = "internal/leaf/helper.go"
)

func TestRepositoryTestSupportRoleTracksImportersAndCache(t *testing.T) {
	dir := newTestSupportModule(t)

	var (
		hits   []string
		hitsMu sync.Mutex
	)

	opts := Options{
		CacheEnabled: true,
		cacheDir:     t.TempDir(),
		CacheHitHook: func(path string) {
			hitsMu.Lock()
			defer hitsMu.Unlock()

			hits = append(hits, path)
		},
	}
	baseline := []string{
		testSupportMixedFile,
		testSupportUnusedFile,
		"support/helper.go",
	}
	production := []string{
		testSupportFixtureFile,
		testSupportLeafFile,
		testSupportMixedFile,
		testSupportUnusedFile,
		"support/helper.go",
	}

	partial := []string{
		"internal/externalfixture/helper.go",
		testSupportFixtureFile,
		testSupportLeafFile,
		testSupportMixedFile,
		testSupportUnusedFile,
	}
	for _, step := range []struct {
		name             string
		pattern          string
		subdir           string
		productionImport bool
		want             []string
		wantHit          string
		wantMisses       []string
	}{
		{name: "cold", pattern: allPackagesPattern, want: baseline},
		{name: "warm", pattern: allPackagesPattern, want: baseline, wantHit: repoAnalysisCacheHitName},
		{name: "add production importer", pattern: allPackagesPattern, productionImport: true, want: production, wantHit: "example.com/sample/internal/externalfixture", wantMisses: []string{"example.com/sample/internal/fixture", "example.com/sample/internal/leaf"}},
		{name: "remove production importer", pattern: allPackagesPattern, want: baseline},
		{name: "partial pattern", pattern: "./internal/...", want: partial},
		{name: "partial directory", pattern: allPackagesPattern, subdir: filepath.Dir(testSupportFixturePath), want: partial},
	} {
		t.Run(step.name, func(t *testing.T) {
			importPath := "example.com/sample/internal/mixed"
			if step.productionImport {
				importPath = "example.com/sample/internal/fixture"
			}

			writeFile(
				t,
				filepath.Join(dir, "sample.go"),
				"package sample\nimport _ "+`"`+importPath+`"`+"\n",
			)

			hits = nil

			issues, err := LintRepository(
				[]string{step.pattern},
				filepath.Join(dir, step.subdir),
				opts,
				nil,
			)
			if err != nil {
				t.Fatal(err)
			}

			panicPackages := issueRelativePaths(t, dir, issues, "prod_must_panic")
			if !slices.Equal(panicPackages, step.want) {
				t.Fatalf("panic packages = %v, want %v", panicPackages, step.want)
			}

			if !strings.Contains(
				joinMessages(issues),
				`condition "s == \"\"" is always false here`,
			) {
				t.Fatalf("test support lost structural finding: %s", joinMessages(issues))
			}

			if step.wantHit != "" && !slices.Contains(hits, step.wantHit) {
				t.Fatalf("cache hits = %v, want hit for %s", hits, step.wantHit)
			}

			for _, path := range step.wantMisses {
				if slices.Contains(hits, path) {
					t.Fatalf("role-changed package reused stale cache: %v", hits)
				}
			}
		})
	}

	pkg := mustPackage(t, loadPackagesForTest(t, dir), "example.com/sample/internal/fixture")
	pass, _ := newAnalysisTestPass(pkg, nil)

	issues, err := RunAnalysis(pass, Options{})
	if err != nil {
		t.Fatal(err)
	}

	if !hasIssueKind(issues, "prod_must_panic") {
		t.Fatalf("single-package analyzer guessed test-only role: %s", joinMessages(issues))
	}
}

func TestTestSupportFilenamesTrackRenamesWithoutSuppressingProduction(t *testing.T) {
	dir := newTestSupportModule(t)
	writeFile(
		t,
		filepath.Join(dir, testSupportFixturePath, "generated.go"),
		"// Code generated by fixture. DO NOT EDIT.\npackage fixture\n",
	)
	writeFile(
		t,
		filepath.Join(dir, testSupportFixturePath, "platform_test_support_"+runtime.GOOS+".go"),
		"package fixture\n",
	)
	writeFile(
		t,
		filepath.Join(dir, testSupportFixturePath, "wrong_test_supportive.go"),
		"package fixture\n",
	)
	writeFile(t, filepath.Join(dir, "production_test_support.go"), `package sample

func Must(err error) {
	if err != nil { panic(err) }
}
`)
	opts := Options{CacheEnabled: true, cacheDir: t.TempDir()}

	issues, err := LintRepository(nil, dir, opts, nil)
	if err != nil {
		t.Fatal(err)
	}

	want := []string{
		"internal/externalfixture/helper.go",
		"internal/fixture/calls.go",
		testSupportFixtureFile,
		"internal/fixture/wrong_test_supportive.go",
		testSupportLeafFile,
	}
	if got := issueRelativePaths(
		t,
		dir,
		issues,
		"test_support_filename",
	); !slices.Equal(
		got,
		want,
	) {
		t.Fatalf("naming diagnostics = %v, want %v", got, want)
	}

	for _, path := range want {
		oldPath := filepath.Join(dir, path)

		newPath := strings.TrimSuffix(oldPath, ".go") + "_test_support.go"
		if err := os.Rename(oldPath, newPath); err != nil {
			t.Fatal(err)
		}
	}

	for range 2 {
		issues, err = LintRepository(nil, dir, opts, nil)
		if err != nil {
			t.Fatal(err)
		}

		if got := issueRelativePaths(t, dir, issues, "test_support_filename"); len(got) != 0 {
			t.Fatalf("renamed files replayed stale naming diagnostics: %v", got)
		}

		if !slices.Contains(
			issueRelativePaths(t, dir, issues, "prod_must_panic"),
			"production_test_support.go",
		) {
			t.Fatalf("filename hid production panic: %s", joinMessages(issues))
		}
	}

	oldPath := filepath.Join(dir, testSupportFixturePath, "helper_test_support.go")

	newPath := filepath.Join(dir, testSupportFixturePath, "misnamed.go")
	if err := os.Rename(oldPath, newPath); err != nil {
		t.Fatal(err)
	}

	issues, err = LintRepository(nil, dir, opts, nil)
	if err != nil {
		t.Fatal(err)
	}

	if got := issueRelativePaths(
		t,
		dir,
		issues,
		"test_support_filename",
	); !slices.Equal(
		got,
		[]string{"internal/fixture/misnamed.go"},
	) {
		t.Fatalf("new bad filename reused clean cache: %v", got)
	}
}

func newTestSupportModule(t *testing.T) string {
	t.Helper()

	dir := newTestModule(t)
	for _, path := range []string{
		testSupportFixturePath, "internal/leaf", "internal/externalfixture",
		testSupportMixedPath, "internal/unused", "support",
	} {
		writeFile(t, filepath.Join(dir, path, "helper.go"), `package `+filepath.Base(path)+`

func Must(err error) {
	if err != nil { panic(err) }
}
`)
	}

	writeFile(t, filepath.Join(dir, testSupportFixturePath, "calls.go"), `package fixture

import (
	"example.com/sample/internal/leaf"
	"example.com/sample/internal/mixed"
)

func Run(err error) { leaf.Must(err); mixed.Must(err) }

func Guard(s string) {
	if s == "" { return }
	if s == "" { println("bad") }
}
`)
	writeFile(t, filepath.Join(dir, "sample_test.go"), `package sample

import (
	"testing"
	"example.com/sample/internal/fixture"
	"example.com/sample/support"
)

func TestFixtures(t *testing.T) { fixture.Run(nil); support.Must(nil) }
`)
	writeFile(t, filepath.Join(dir, "external_test.go"), `package sample_test

import (
	"testing"
	"example.com/sample/internal/externalfixture"
)

func TestExternalFixture(t *testing.T) { externalfixture.Must(nil) }
`)
	writeFile(t, filepath.Join(dir, "internal/unused", "own_test.go"), `package unused_test

import (
	"testing"
	"example.com/sample/internal/unused"
)

func TestOwnAPI(t *testing.T) { unused.Must(nil) }
`)

	writeFile(t, filepath.Join(dir, "sample.go"), `package sample
import _ "example.com/sample/internal/mixed"
`)

	return dir
}
