package lint

import (
	"go/ast"
	"go/parser"
	"go/token"
	"path/filepath"
	"testing"
)

func TestPackageRepoFilesExcludeCompilerGeneratedCGoFiles(t *testing.T) {
	t.Parallel()

	const testSourceFilename = "sample.go"

	dir := t.TempDir()
	generated := filepath.Join(t.TempDir(), "_cgo_gotypes.go")

	files, err := packageRepoFiles(&packageMeta{
		Dir:             dir,
		ImportPath:      "example.com/sample",
		GoFiles:         []string{testSourceFilename},
		CgoFiles:        []string{"native.go"},
		CompiledGoFiles: []string{testSourceFilename, generated},
	})
	if err != nil {
		t.Fatal(err)
	}

	want := []string{filepath.Join(dir, testSourceFilename), filepath.Join(dir, "native.go")}
	if len(files) != len(want) || files[0] != want[0] || files[1] != want[1] {
		t.Fatalf("source files = %#v, want %#v", files, want)
	}
}

func TestPackageAnalysisFilesDropOnlyGeneratedCompilerCacheFiles(t *testing.T) {
	t.Parallel()

	packageDir := t.TempDir()
	fset := token.NewFileSet()

	repoFile, err := parser.ParseFile(
		fset,
		filepath.Join(packageDir, "generated.go"),
		"// Code generated by test. DO NOT EDIT.\npackage sample\n",
		parser.ParseComments,
	)
	if err != nil {
		t.Fatal(err)
	}

	compilerFile, err := parser.ParseFile(
		fset,
		filepath.Join(t.TempDir(), "_cgo_gotypes.go"),
		"// Code generated by cmd/cgo; DO NOT EDIT.\npackage sample\n",
		parser.ParseComments,
	)
	if err != nil {
		t.Fatal(err)
	}

	got := packageAnalysisFiles([]*ast.File{repoFile, compilerFile}, fset, packageDir)
	if len(got) != 1 || got[0] != repoFile {
		t.Fatalf("analysis files = %#v, want repo generated file only", got)
	}
}
